### ISSUE TITLE
Implement single interrupt termination

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/wtfuzz#1]
At the moment you need to enter one KeyboardInterrupt per thread to halt the program, this should be a single interrupt.

**Comment by prabodh1194** [comment]
It'll be great if you can provide a reproducible example.

**Comment by mattjegan** [comment]
Hey @prabodh1194 here is an example of the issue. As you can see, the whole program doesn't terminate on my first `KeyboardInterrupt` (^C). Ideally, we would only want to do this once and have all the threads killed.

```python
python wtfuzz/wtfuzz.py mattjegan.com list.txt
Prepending protocol: http://mattjegan.com
404 : http://mattjegan.com/www
404 : http://mattjegan.com/mail
404 : http://mattjegan.com/remote
404 : http://mattjegan.com/blog
^C404 : http://mattjegan.com/webmail
404 : http://mattjegan.com/server
404 : http://mattjegan.com/ns1
^CTraceback (most recent call last):
  File "wtfuzz/wtfuzz.py", line 48, in run
    for f in as_completed(futures):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py", line 215, in as_completed
    waiter.event.wait(wait_timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wtfuzz/wtfuzz.py", line 149, in <module>
    if __name__ == '__main__': main()
  File "wtfuzz/wtfuzz.py", line 147, in main
    wtfuzz.run()
  File "wtfuzz/wtfuzz.py", line 49, in run
    f.result()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py", line 581, in __exit__
    self.shutdown(wait=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/thread.py", line 139, in shutdown
    t.join()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
404 : http://mattjegan.com/ns2
404 : http://mattjegan.com/smtp
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/thread.py", line 39, in _python_exit
    t.join()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by prabodh1194** [comment]
Thought so. I think I have ideas. Let me send you a PR for this.

**Comment by mattjegan** [comment]
No worries, I look forward to it 😄
